name: Build AtmoXL-Titel-Installer

on:
  [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Update packages
      run: |
        sudo -n apt-get update
        sudo -n apt-get upgrade -y patch autoconf automake diffutils pkgconf fakeroot git file tar bzip2 zstd
        sudo -n dkp-pacman --noconfirm -U \
          "https://wii.leseratte10.de/devkitPro/other-stuff/dkp-toolchain-vars-1.0.2-1-any.pkg.tar.xz"

    - name: Silence all git safe directory warnings
      run: git config --system --add safe.directory '*'

    - name: Checkout latest libnx commit
      run: |
        git clone --recurse-submodules https://github.com/R-YaTian/libnx.git

    - name: Checkout latest libusbhsfs commit
      run: |
        git clone https://github.com/DarkMatterCore/libusbhsfs.git

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build and install libnx
      run: |
        cd libnx
        make install -j$(nproc)

    - name: Build libusbhsfs dependencies
      run: |
        cd libusbhsfs
        make BUILD_TYPE=GPL install

    - name: Build AtmoXL-Titel-Installer
      run: |
        make -j$(nproc)

    - uses: actions/upload-artifact@master
      with:
        name: AtmoXL-Titel-Installer
        path: AtmoXL-Titel-Installer.nro
        if-no-files-found: error
